apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name:  nginx

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: nginx
      spec:
        containers:
        - name: nginx
          image: docker.io/library/nginx:latest
          ports:
          - containerPort: 80

- apiVersion: v1
  kind: Service
  metadata:
    name:  nginx-svc
  spec:
    selector:
      name: nginx
    type:  LoadBalancer
    ports:
    - name:  http
      port:  80
      targetPort:  80