apiVersion: v1
kind: List
metadata:
  namespace: wordpress
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: wordpress
  spec:
    resources:
      requests:
        storage: 2Gi
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce
- apiVersion: v1
  kind: Deployment
  metadata:
    name: wordpress 
    labels:
      name:  wordpress
  spec:
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          name:  wordpress
      spec:
        containers:
        - image:  docker.io/library/wordpress:php8.1-apache
          name:  wordpress
          resources:
            requests:
              cpu: "20m"
              memory: "55Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          # livenessProbe:
          #   httpGet:
          #     path: /_status/healthz
          #     port: 5000
          #   initialDelaySeconds: 90
          #   timeoutSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /_status/healthz
          #     port: 5000
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 10
          env:
          - name:  ENVVARNAME
            value:  ENVVARVALUE       
          ports:
          - containerPort:  80
            name:  http
          volumeMounts:
          - mountPath: /data
            name: data
        volumes:
          - name: data
            emptyDir: {}
        restartPolicy: Always
        imagePullPolicy: Always